---
created: 2022-12-12
title: 자바스터디_08_예외처리
author: pej
category: study
tag: study
aliases: [자바스터티_08_예외처리]
---

#### 책 목차
	- 예외처리(Exception Handling)


#### 학습할 것
	- 예외 클래스의 계층 구조
	- 예외 처리 정의와 방법
	- 사용자정의 예외 만드는 방법

#### 학습 내용

1. 에러
	+ 정의 : 실행중 오작동하거나 비정상적으로 종료되는 것을 의미
	+ 종류
		+ 컴파일 에러 : 컴파일시에 발생하는 에러
		+ 런타임 에러 : 실행시 발생하는 에러
		+ 논리적 에러 : 실행은 정상적으로 되지만 의도와 다르게 동작하는 것

> 에러(Error)와 예외(Exception)
> + 공통점 : 런타임시 발생함
> + 차이점 : **예외(Exception)는 코드로 예방이 가능한 오류이며 에러(Error)는 코드로도 예방 할 수 없음**

2. 예외 클래스의 계층구조
  ![계층구조](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fbh9TMG%2FbtqTvShdZ7K%2FQ8xs0urXoEzbUagqdv72z1%2Fimg.jpg)

  + RuntiemException 클래스
    + 개발자의 실수로 발생하는 예외
    + **예외 처리를 필수로 안 해도 됨(Unchekcd Exception)**
    + 런타임시 확인함
    + 예) IndexOutOfBoundsException, NullPointException 등등
  + Exception 클래스
    + 외적인 요인에 의해서 발생하는 예외
    + **예외 처리를 필수로 해야 됨(Cheked Exception)**
    + 컴파일시 확인함
    + 예) FileNotFoundException, ClassNotFoundException 등등

3. 예외 처리
	+ 정의 : 정상적인 실행상태를 유지하기 위해서 발생 할 수 있는 예외에 대비하는 코드를 작성하는 것
	+ **try-catch-finally**
	```
	try { 
		// 예외가 발생할 수 있는 부분 
	} catch (Exception e) { 
		// 예외 발생시 처리 내용 
	} finally { 
		// 예외 발생 여부와 상관없이 항상 수행되어야 하는 내용 
	}
	```
	```
	public class TestException {
		public static void main(String args[]) {
			try {
				throw new NullPointerException();
			} catch (NullPointerException e) {
				System.out.println("## NullPointerException ##");
			} catch (IndexOutOfBoundsException e) {
				System.out.println("## IndexOutOfBoundsException ##");
			}
		}
	}
	[결과]
	## NullPointerException ##
	```
	![try-catch문흐름](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FuWWfl%2FbtqTEMomC5l%2Ftwye8H8DpQZtZXKoEkUcC0%2Fimg.png)
	+ 예외가 발생하면 발생한 예외에 해당하는 클래스의 인스턴스가 만들어짐
	+ 생성한 참조변수는 상수이므로 값을 변경할 수 없음
	+ catch문을 차례대로 내려가면서 instanceof 연산자를 이용하여 발생한 예외와 일치하는 블록인지 확인하며 일치하는 것이 없을 경우 그 예외는 처리되지 못함
	
> pritStackTrace()와 getMessage()
> + pritStackTrace() : 예외 발생시 호출스택에 있었던 메서드 정보와 예외 메세지를 console에 출력함 소스 취약점으로 걸릴 수 있으니 가급적 사용하지 않는 것이 좋음
> + getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메세지를 보여줌(기본값:null)
> ```
> try {
>     throw new NullPointerException("메세지 저장");
> } catch (NullPointerException e) {
>     System.out.println("## NullPointerException ##");
>     e.printStackTrace();
>     System.out.println("## getMessage => " + e.getMessage());
> >
> [결과]
> ## NullPointerException ##
> java.lang.NullPointerException: 메세지 저장
> 	at ch08.TestException.main(TestException.java:6)
> ## getMessage => 메세지 저장
> ```

> 멀티 catch블럭
> + JDK 1.7부터 여러 catch블럭을 하나의 블록으로 합칠 수 있게 되었음
> + 연결된 예외 클래스가 상속관계이면 에러 발생함(둘다 있을 필요가 없기때문에)
> ```
> try {
>     throw new NullPointerException();
> } catch (NullPointerException | IndexOutOfBoundsException e) {
>     // 멀티 catch문을 이용하면 이렇게 Exception마다 개별 처리 할 수도 있음
>     if ( e instanceof NullPointerException ) {
>         System.out.println("## NullPointerException ##");
>     } else if (e instanceof IndexOutOfBoundsException) {
>         System.out.println("## IndexOutOfBoundsException ##");
>     }
> }
> ```

> try-with-resources(자동 자원 반환)
> + JDK 1.7부터 추가되었으며 try 블록이 끝나면 자동으로 자원을 종료해줌
> + 이때 종료될 수 있는 자원은 AutoCloseable 인터페이스의 구현체여야 함
> ```
> try (FileInputStream fis = new FileInputStream("")) {
>     
> } catch (IOException e) {
>     
> }
> ```

4. 사용자정의 예외 만들기
	+ 알맞은 예외 클래스를 상속받아서 새로운 예외 클래스를 만들 수 있음
	```
	public class MyException extends Exception {
    
	    private static final long serialVersionUID = 1L;
	
	    MyException(String msg) {
	        super(msg);
	    }
	}
	```

5. 예외 되던지기(exception re-throwing)
	+ 양쪽 메서드에서 모두 try-catch문이 되어 있어야하고 하나의 예외에 대해서 양쪽 모두 처리할 작업이 있는 경우에 사용함[^1]
	```
	public static void main(String args[]) {
      try {
          test();
      } catch (Exception e) {
          System.out.println("## main -catch ##");
      }
    }
    
    public static void test() throws Exception {
      try {
          // 예외 강제로 발생
          throw new Exception();
      } catch (Exception e) {
          System.out.println("## catch ##");
          // 예외 다시 던지기
          throw e;
      }
    }
	```

6. 연결된 예외(chained exception)[^1]
	+ 어떤 예외를 다른 예외로 감싸는 것
	+ 사용이유
		+ 여러 예외를 하나로 묶어서 사용하기 위해서
		+ checked 예외를 unchecked 예외로 변경하기 위해서

#### 출처(참고문헌)
- Java의 정석
- https://www.nextree.co.kr/p3239/
- https://ryan-han.com/post/java/try_with_resources/
- https://velog.io/@oyeon/8-18-%EC%97%B0%EA%B2%B0%EB%90%9C-%EC%98%88%EC%99%B8

#### 연결문서
-

#### 각주
[^1]: 해당 방식이 실제 코드에서 사용하는지 찾아보면 좋을것같다.
